In [1]:
import pandas as pd

from aula_1 import dados

df = pd.read_csv('csv/fifa.csv')
df.head() # No Jupyter, você não precisa de print() na última linha da célula

Minha tabela de compras
  Produto  Preço  Quantidade
0   Leite    5.0           2
1     Pao    3.5           5
2    Café   15.0           1
3   Arroz   20.0           2

--- Tabela com o total calculado___

___Filtros que custam mais de R$ 10,00 reais___
  Produto  Preço  Quantidade  Total
2    Café   15.0           1   15.0
3   Arroz   20.0           2   40.0

___Filtros que custam menos de R$ 10,00 reais___
  Produto  Preço  Quantidade  Total
0   Leite    5.0           2   10.0
1     Pao    3.5           5   17.5
Total gasto economicos R$: 27.50
Total de itens caros R$: 40.00
 O item mais caro da lista é:  Arroz

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [2]:
df[['Name','Age']].head()

                Name  Age
0           L. Messi   31
1  Cristiano Ronaldo   33
2          Neymar Jr   26
3             De Gea   27
4       K. De Bruyne   27

In [3]:
df[['Club','Penalties']].head()

                  Club  Penalties
0         FC Barcelona       75.0
1             Juventus       85.0
2  Paris Saint-Germain       81.0
3    Manchester United       40.0
4      Manchester City       79.0

In [4]:
df.head(2) # mostra os primeiros

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M

In [5]:
df.tail() # mostra os ultimos

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [6]:
df.columns # todas as colunas

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [7]:
df.iloc[15] #mostra apenas o selecionado

Unnamed: 0                                                    15
ID                                                        211110
Name                                                   P. Dybala
Age                                                           24
Photo             https://cdn.sofifa.org/players/4/19/211110.png
                                       ...
GKHandling                                                   4.0
GKKicking                                                    4.0
GKPositioning                                                5.0
GKReflexes                                                   8.0
Release Clause                                           €153.5M
Name: 15, Length: 89, dtype: object

In [8]:
df.iloc[6,4]

'https://cdn.sofifa.org/players/4/19/177003.png'

In [9]:
df.loc[df['Nationality']== 'Argentina']

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
15,15,211110,P. Dybala,24,https://cdn.sofifa.org/players/4/19/211110.png,Argentina,https://cdn.sofifa.org/flags/52.png,89,94,Juventus,...,84.0,23.0,20.0,20.0,5.0,4.0,4.0,5.0,8.0,€153.5M
23,23,153079,S. Agüero,30,https://cdn.sofifa.org/players/4/19/153079.png,Argentina,https://cdn.sofifa.org/flags/52.png,89,89,Manchester City,...,90.0,30.0,20.0,12.0,13.0,15.0,6.0,11.0,14.0,€119.3M
38,38,167664,G. Higuaín,30,https://cdn.sofifa.org/players/4/19/167664.png,Argentina,https://cdn.sofifa.org/flags/52.png,88,88,Milan,...,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
43,43,201399,M. Icardi,25,https://cdn.sofifa.org/players/4/19/201399.png,Argentina,https://cdn.sofifa.org/flags/52.png,87,90,Inter,...,85.0,45.0,24.0,20.0,13.0,9.0,5.0,7.0,9.0,€114.5M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17349,17349,240955,T. Durso,19,https://cdn.sofifa.org/players/4/19/240955.png,Argentina,https://cdn.sofifa.org/flags/52.png,54,74,Gimnasia y Esgrima La Plata,...,37.0,15.0,13.0,10.0,57.0,54.0,53.0,57.0,54.0,€300K
17355,17355,237125,V. Barbero,17,https://cdn.sofifa.org/players/4/19/237125.png,Argentina,https://cdn.sofifa.org/flags/52.png,54,73,Belgrano de Córdoba,...,52.0,16.0,25.0,25.0,14.0,7.0,11.0,7.0,9.0,€291K
17638,17638,236431,E. Alarcón,25,https://cdn.sofifa.org/players/4/19/236431.png,Argentina,https://cdn.sofifa.org/flags/52.png,53,57,Patronato,...,47.0,12.0,10.0,14.0,56.0,55.0,55.0,50.0,52.0,€76K
17861,17861,245726,F. Bustamante,19,https://cdn.sofifa.org/players/4/19/245726.png,Argentina,https://cdn.sofifa.org/flags/52.png,52,66,Club Atlético Tigre,...,44.0,49.0,42.0,46.0,6.0,8.0,7.0,7.0,9.0,€234K
17987,17987,241099,L. Finochietto,21,https://cdn.sofifa.org/players/4/19/241099.png,Argentina,https://cdn.sofifa.org/flags/52.png,51,59,Argentinos Juniors,...,33.0,15.0,11.0,13.0,57.0,51.0,54.0,52.0,50.0,€66K

In [10]:
df.sort_values(['Name', 'Age', 'Weight']) #mostra essas informacoes

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
13632,13632,228006,A. Abang,21,https://cdn.sofifa.org/players/4/19/228006.png,Cameroon,https://cdn.sofifa.org/flags/103.png,62,69,New York Red Bulls,...,45.0,32.0,17.0,21.0,6.0,6.0,7.0,13.0,9.0,€723K
15665,15665,243896,A. Abdellaoui,25,https://cdn.sofifa.org/players/4/19/243896.png,Algeria,https://cdn.sofifa.org/flags/97.png,59,64,FC Sion,...,51.0,61.0,66.0,65.0,15.0,10.0,14.0,13.0,14.0,€259K
3055,3055,198076,A. Abdennour,28,https://cdn.sofifa.org/players/4/19/198076.png,Tunisia,https://cdn.sofifa.org/flags/145.png,73,73,Olympique de Marseille,...,75.0,68.0,73.0,75.0,12.0,8.0,7.0,8.0,15.0,NaN
6388,6388,138698,A. Abdi,31,https://cdn.sofifa.org/players/4/19/138698.png,Switzerland,https://cdn.sofifa.org/flags/47.png,69,69,Sheffield Wednesday,...,75.0,47.0,60.0,57.0,9.0,6.0,8.0,11.0,8.0,€1.7M
12816,12816,245438,A. Abdu Jaber,21,https://cdn.sofifa.org/players/4/19/245438.png,Eritrea,https://cdn.sofifa.org/flags/113.png,63,65,Al Wehda,...,49.0,17.0,13.0,15.0,7.0,11.0,7.0,6.0,12.0,€843K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,15334,246284,Óscar Gil,20,https://cdn.sofifa.org/players/4/19/246284.png,Spain,https://cdn.sofifa.org/flags/45.png,59,69,Elche CF,...,45.0,53.0,65.0,66.0,14.0,14.0,11.0,8.0,11.0,€385K
9803,9803,229865,Óscar Pinchi,22,https://cdn.sofifa.org/players/4/19/229865.png,Spain,https://cdn.sofifa.org/flags/45.png,66,77,Atlético Madrid,...,63.0,50.0,39.0,34.0,5.0,12.0,6.0,12.0,13.0,€2.5M
2564,2564,208621,Óscar Plano,27,https://cdn.sofifa.org/players/4/19/208621.png,Spain,https://cdn.sofifa.org/flags/45.png,74,74,Real Valladolid CF,...,69.0,31.0,30.0,26.0,8.0,14.0,16.0,8.0,13.0,€13.2M
10353,10353,243558,Óscar Valentín,23,https://cdn.sofifa.org/players/4/19/243558.png,Spain,https://cdn.sofifa.org/flags/45.png,65,71,CF Rayo Majadahonda,...,60.0,66.0,63.0,65.0,11.0,8.0,13.0,10.0,8.0,€1.3M
10002,10002,220433,Óscar Whalley,24,https://cdn.sofifa.org/players/4/19/220433.png,Spain,https://cdn.sofifa.org/flags/45.png,65,70,Aarhus GF,...,51.0,23.0,18.0,16.0,66.0,65.0,68.0,63.0,66.0,€696K

In [11]:
df['Total'] = df['Acceleration'] + df['Agility'] + df['Reactions']
df  #adiciona uma coluna

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Total
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,277.0
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,272.0
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,284.0
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,207.0
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,248.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K,163.0
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K,119.0
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K,167.0
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K,134.0
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K,163.0

In [12]:
df = df[['Name', 'Nationality', 'Total']]
df.sort_values('Total', ascending=False)

                 Name     Nationality  Total
2           Neymar Jr          Brazil  284.0
5           E. Hazard         Belgium  279.0
0            L. Messi       Argentina  277.0
26           M. Salah           Egypt  276.0
25          K. Mbappé          France  275.0
...               ...             ...    ...
13279    P. Mazzocchi           Italy    NaN
13280       Y. Ammour          France    NaN
13281  Jwa Joon Hyeop  Korea Republic    NaN
13282      O. Marrufo          Mexico    NaN
13283     Han Pengfei        China PR    NaN

[18207 rows x 3 columns]

In [16]:
df.to_csv('Teste1.csv', index=False) # aqui ele cria um arquivo novo alterado e exclui a coluna index q foi gerada

In [17]:
df.to_excel('Teste2.xlsx', index=False)

In [19]:
df.to_csv('Teste3.txt', index=False, sep='\t')